version: '3'

services:
  casa-mqtt:
    image: roeldev/casa-mosquitto
    container_name: casa-mqtt
    build: .
    env_file:
      - .docker.env
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
