#!/bin/bash

LABEL_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
LABEL_VCS_REF=$(git rev-parse --short HEAD)

echo "docker build \
    --build-arg LABEL_BUILD_DATE=${LABEL_BUILD_DATE} \
    --build-arg LABEL_VCS_REF=${LABEL_VCS_REF} \
    -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} ."

docker build \
    --build-arg LABEL_BUILD_DATE=${LABEL_BUILD_DATE} \
    --build-arg LABEL_VCS_REF=${LABEL_VCS_REF} \
    -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .
